/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[333] =
    {   0,
        0,    0,   93,   91,   85,   90,   89,   38,   81,   91,
       91,   82,   82,   88,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   90,   80,    0,    0,   87,   82,    0,   88,
       87,   86,   23,   87,   63,   19,    0,   53,   87,   59,
        6,    7,   87,   78,   87,   76,   10,   87,   16,   13,
       39,   50,    8,   87,   52,   14,   40,   87,   15,   51,
       71,   65,   87,   31,   87,   12,   87,   61,   35,   75,

       49,   54,   87,   69,   87,   57,    2,   87,    3,   27,
       67,   87,   87,    4,    5,   23,   87,   63,   19,   87,
       87,   87,   10,   87,   39,   87,   40,   87,   87,   87,
       31,   12,   87,   35,   87,   87,    2,   87,   27,   67,
       87,   87,   74,   87,    0,   83,    0,   87,   87,   87,
        0,   87,   84,   87,   87,   87,    0,   87,   41,   72,
       87,   87,   87,    0,   87,   87,    0,   87,   87,   87,
       87,   54,    1,   87,   87,   37,    0,   87,   87,   87,
        0,   87,   87,    0,   87,   87,   87,   87,    0,   87,
       87,   87,   87,   87,   87,    0,    0,   87,   87,   87,

       87,    0,   87,   87,   87,   21,   55,   87,   87,   17,
       87,   87,   87,   42,    9,   87,   36,   87,   87,   29,
       87,   87,   11,   73,    0,   87,   87,   87,   87,   25,
       87,   34,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,    0,   87,   87,   87,   87,    0,   87,
       46,   87,   87,   43,   87,   87,   47,   87,   87,    0,
        0,    0,    0,   87,   87,   87,   87,   48,   66,   77,
       87,   87,   87,   87,   87,   87,   87,    0,    0,    0,
        0,   87,   87,   55,   62,   87,   87,   87,   87,   70,
       64,   24,   20,   33,   32,   28,   87,   87,   87,   87,

       87,   87,   87,   87,   24,   20,   32,   28,   87,   87,
       87,   58,   79,   44,    0,    0,    0,    0,   45,   68,
       56,   87,    0,    0,    0,    0,   60,   22,   18,   30,
       26,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    6,    1,    1,    1,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   13,   14,
       15,   15,   15,   15,   15,   16,   16,   17,   18,    1,
       19,    1,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   29,   42,   29,   29,
        1,    1,    1,    1,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   29,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   29,   65,
       29,   29,    1,   66,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    4,
        1,    3,    3,    3,    3,    3,    5,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[338] =
    {   0,
        0,    0,  333, 1151, 1151,    0, 1151, 1151,  297,  305,
        0,   57,   64,    0,   65,   76,   88,   75,   99,  100,
      101,  109,  129,  110,  153,  183,  114,  119,  139,  195,
      135,  203,  189,  184,  229,  239,  147,  173,  168,  206,
      240,  248,  295,  258,  254,  260,  274,  311,  321,  320,
      330,  222,    0, 1151,  262,  295,    0,  346,  384,    0,
      113, 1151,  169,  257,  143,  263,   71,  249,  259,  265,
      268,  276,  332,  334,  353,  354,  356,  378,  393,  401,
      402,  403,  404,  406,  407,  417,  425,  426,  429,  430,
      431,  439,  440,  441,  444,  443,  445,  453,  456,  457,

      458,  473,  481,  482,  483,  485,  486,  491,  496,  497,
      499,  501,  505,  502,  510,  511,  513,  516,  522,  525,
      526,  528,  530,  536,  538,  542,  541,  544,  552,  550,
      553,  554,  558,  556,  564,  567,  566,  569,  572,  578,
      575,  583, 1151, 1151,  272,    0,  569,  609,  599,  615,
      605,  600,   82,  591,  629,  626,  618,  637,  631,  639,
      640,  642,  650,  636,  652,  666,  649,  667,  662,  675,
      677,  680,  688,  689,  691,  693,  667,  702,  705,  706,
      696,  707,  711,  698,  720,  721,  726,  730,  723,  731,
      736,  740,  744,  742,  753,  729,  740,  755,  763,  761,

      774,  770,  788,  791,  796, 1151,  800,  802,  804, 1151,
      814,  810,  815,  816, 1151,  818,  827,  832,  828, 1151,
      840,  841, 1151,  844,  833,  846,  852,  858,  860, 1151,
      863,  862,  866,  868,  872,  874,  876,  877,  888,  891,
      893,  892,  894,  869,  897,  906,  909,  910,  948,  911,
      912,  915,  923,  928,  931,  936,  932,  949,  950,   92,
      231,  210,  206,  955,  961,  966,  971,  972,  974,  980,
      983,  988,  994,  996, 1000,  999, 1004,   51,  189,  172,
      171, 1005, 1008, 1151, 1002, 1010, 1013, 1014, 1018, 1016,
     1019,  223,  209, 1151,  208,  207, 1045, 1024, 1047, 1048,

     1030, 1049, 1051, 1053,  204,  193,  179,  174, 1062, 1068,
     1070, 1071, 1072, 1073,  158,  147,  133,  129, 1074, 1076,
     1082, 1084,  101,   86,   82,   54, 1085, 1151, 1151, 1151,
     1151, 1151, 1135, 1138,   65, 1142, 1145
    } ;

static yyconst short int yy_def[338] =
    {   0,
      332,    1,  332,  332,  332,  333,  332,  332,  332,  334,
      335,  334,  334,  336,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,   26,  337,  337,  337,  337,  337,  337,
      337,  332,  333,  332,  334,  332,  335,  334,  334,  336,
      337,  332,  337,  337,  337,  337,  332,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  332,  332,  332,   59,  332,  337,  337,  337,
      332,  337,  332,  337,  337,  337,  332,  337,  337,  337,
      337,  337,  337,  332,  337,  337,  332,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  332,  337,  337,  337,
      332,  337,  337,  332,  337,  337,  337,  337,  332,  337,
      337,  337,  337,  337,  337,  332,  332,  337,  337,  337,

      337,  332,  337,  337,  337,  332,  337,  337,  337,  332,
      337,  337,  337,  337,  332,  337,  337,  337,  337,  332,
      337,  337,  332,  337,  332,  337,  337,  337,  337,  332,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  332,  337,  337,  337,  337,  332,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  332,
      332,  332,  332,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  332,  332,  332,
      332,  337,  337,  332,  337,  337,  337,  337,  337,  337,
      337,  332,  332,  332,  332,  332,  337,  337,  337,  337,

      337,  337,  337,  337,  332,  332,  332,  332,  337,  337,
      337,  337,  337,  337,  332,  332,  332,  332,  337,  337,
      337,  337,  332,  332,  332,  332,  337,  332,  332,  332,
      332,    0,  332,  332,  332,  332,  332
    } ;

static yyconst short int yy_nxt[1218] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       11,   12,   13,   13,   13,   13,    4,   14,    4,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   24,
       25,   26,   27,   28,   29,   24,   30,   31,   32,   33,
       24,   24,   10,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   24,   43,   44,   45,   46,   47,   24,   48,
       49,   50,   51,   24,   24,   52,   56,   57,   58,   58,
       58,   58,   58,   56,   56,   58,   58,   58,   58,   58,
       67,   62,  153,  153,   56,   56,   63,   68,   68,   68,
       68,   62,   62,  153,  153,   64,  305,   56,   59,  331,

       71,   72,   65,   69,   62,   66,   76,   73,   56,   56,
       56,   74,   70,  292,  306,   62,   62,   62,   56,   56,
       75,   59,   56,   56,   79,   62,   62,  330,   56,   62,
       62,  329,  293,   78,   77,   62,   81,   96,   56,   80,
       82,   82,   82,   82,   56,   62,  328,   97,   56,   98,
      331,   62,   56,   83,  330,   62,   56,  104,  105,   62,
       99,   84,   56,   62,   85,   85,   85,   85,  329,   62,
      100,  106,  107,  108,  109,  110,   86,   56,  147,  328,
      101,  150,   56,  326,   62,   62,   87,   88,  325,   62,
      148,   89,   56,   56,   90,   90,   90,   90,   56,   62,

       62,   76,  324,   91,   56,   62,  102,  102,  102,  102,
      102,   62,   56,  323,   92,   56,  318,  317,  316,   62,
       93,  113,   62,   94,  124,   95,  114,  103,  115,  116,
      111,  123,  315,   67,  308,  307,  294,  117,   56,  112,
       68,   68,   68,   68,  118,   62,  296,  119,   56,   56,
      295,   71,   72,   79,  294,   62,   62,   56,   56,   82,
       82,   82,   82,   56,   62,   62,   56,   80,   56,   56,
       62,   56,  151,   62,   56,   62,   62,   56,   61,   62,
      120,   62,  121,   56,   62,   56,   74,  143,   70,   61,
       62,  125,   62,  144,  122,   61,   83,  154,   61,  149,

      129,  132,   91,  126,   56,  152,   85,   85,   85,   85,
      133,   62,   92,   98,   56,   54,  144,  144,  130,  134,
       56,  131,  102,  102,  102,  102,  102,   62,  100,   56,
       56,  145,  332,  332,  332,  332,   62,   62,  101,   56,
      144,   56,   86,   56,  332,  332,   62,  332,   62,  332,
       62,  127,  128,  155,  145,   56,   89,   58,   58,   58,
       58,   58,   56,   56,  332,  157,  135,  104,  136,   62,
       62,  140,   62,  332,  332,  332,  332,  332,  332,  141,
      106,  137,  138,  109,  139,  142,  332,   56,  332,  332,
      114,  156,  115,   56,   62,  146,  146,  146,  146,  146,

      332,  332,   56,  146,  146,  146,  146,  146,  146,   62,
       56,   56,   56,   56,  158,   56,   56,   62,   62,   62,
       62,  332,   62,   62,  332,  332,   56,  146,  146,  146,
      146,  146,  146,   62,   56,   56,  332,  332,   56,   56,
       56,   62,   62,  159,  160,   62,   62,   62,   56,   56,
      164,  332,  167,   56,   56,   62,   62,   62,  161,   62,
       62,   62,   56,  162,  165,   56,   56,   56,  332,   62,
      332,  332,   62,   62,   62,  166,  332,  168,  163,  332,
      332,  332,   56,  169,  172,  172,  172,  172,  172,   62,
       56,   56,   56,  170,   56,   56,  332,   62,   62,   62,

       56,   62,   62,  173,  174,   56,  177,   62,   56,  332,
       56,   56,   62,   62,   56,   62,  171,   62,   62,   56,
      181,   62,   56,  332,  175,   56,   62,   62,  176,   62,
      178,  184,   62,  332,   56,   56,  332,   56,   62,  189,
      179,   62,   62,  180,   62,   56,   62,   56,  332,  332,
       56,   56,   62,   56,   62,  182,  148,   62,   62,   56,
       62,   56,  196,  197,  185,   56,   62,   56,   62,   62,
       62,  187,   62,   56,   62,   56,   56,  183,   56,  332,
       62,  202,   62,   62,   56,   62,  186,   56,   62,  188,
      206,   62,   56,  332,   62,  190,  193,  191,  332,   62,

       56,  332,  159,  160,  192,  145,  194,   62,   56,   56,
      173,  195,  200,  198,  144,   62,   62,  332,   56,  199,
      207,  207,  207,  207,   56,   62,  210,  201,  145,  176,
      211,   62,  203,  212,  209,   56,  208,  204,   56,  215,
       56,  145,   62,  332,  205,   62,   56,   62,   56,   56,
      144,   56,  332,   62,  145,   62,   62,  220,   62,   56,
      216,   56,  214,  144,  145,  225,   62,  213,   62,  219,
      223,   56,  145,  332,  217,   56,   56,  145,   62,  221,
      218,  144,   62,   62,   56,  145,   56,  332,  230,   56,
      224,   62,  332,   62,  144,  145,   62,   56,   56,  222,

       56,  332,   56,  145,   62,   62,  332,   62,  145,   62,
      229,   56,  144,  226,   56,   56,   56,  144,   62,  144,
       56,   62,   62,   62,  332,  231,  145,   62,  232,   56,
       56,  228,  145,  233,  145,   56,   62,   62,  227,   56,
       56,  206,   62,  210,  144,   56,   62,   62,  332,   56,
      144,   56,   62,   56,  235,  145,   62,  145,   62,  145,
       62,  144,   56,  237,   56,  145,  244,  234,  215,   62,
       56,   62,   56,  236,  220,  332,  145,   62,  239,   62,
      332,  332,  145,   56,  332,  223,  332,  238,  145,  214,
       62,  144,  332,  217,  332,  241,  243,   56,  242,  145,

       56,  240,  224,  245,   62,   56,  145,   62,  332,  249,
      332,   56,   62,   56,  332,  230,   62,  246,   62,   56,
       62,  250,  332,   56,   56,   56,   62,   56,  332,  145,
       62,   62,   62,  252,   62,  247,   56,   56,  232,  332,
      332,   56,  251,   62,   62,  254,  253,  248,   62,   56,
       56,  256,  260,   56,  261,   56,   62,   62,  255,  258,
       62,   56,   62,  259,  262,  264,  257,   56,   62,   56,
      263,   56,   56,  332,   62,   56,   62,   56,   62,   62,
      266,   56,   62,   56,   62,   56,   56,  332,   62,  332,
       62,  332,   62,   62,  267,  265,  270,   56,  268,  269,

       56,   56,   56,   56,   62,  332,   56,   62,   62,   62,
       62,  271,  278,   62,  279,   56,  332,  272,   56,   56,
       56,   56,   62,  280,   56,   62,   62,   62,   62,  281,
      254,   62,   56,  251,  275,  273,  276,   56,  277,   62,
       56,   56,  332,  282,   62,   56,  287,   62,   62,  285,
      332,  274,   62,  286,  288,  257,  283,  289,   56,   56,
      332,  332,  332,  270,   56,   62,   62,  268,  269,  144,
       56,   62,  332,  291,  284,   56,  297,   62,  284,  284,
       56,   56,   62,   56,  145,  299,  290,   62,   62,   56,
       62,  332,   56,  144,  300,  332,   62,   56,  284,   62,

      332,  284,  284,   56,   62,   56,  298,  145,   56,   56,
       62,   56,   62,   56,   56,   62,   62,   56,   62,   56,
       62,   62,   56,   56,   62,   56,   62,   56,   56,   62,
       62,  311,   62,   56,   62,   62,  332,  332,  332,   56,
       62,  302,  332,  303,  285,  304,   62,  314,  309,  301,
      313,  291,  332,  312,   56,  310,   56,   56,   56,  290,
       56,   62,   56,   62,   62,   62,  332,   62,  332,   62,
      332,   56,  320,  321,  319,  322,  319,   56,   62,   56,
       56,   56,   56,   56,   62,   56,   62,   62,   62,   62,
       62,   56,   62,   56,   56,  332,  327,  332,   62,  332,

       62,   62,  332,  332,  332,  314,  332,  332,  332,  332,
      313,  320,  312,  332,  332,  332,  332,  321,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  327,   53,  332,   53,   53,   53,
       55,   55,   60,  332,   60,   60,   60,   61,   61,   61,
        3,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332
    } ;

static yyconst short int yy_chk[1218] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   12,  335,   12,   12,
       12,   12,   12,   13,   15,   13,   13,   13,   13,   13,
       16,   15,   67,   67,   18,   16,   15,   16,   16,   16,
       16,   18,   16,  153,  153,   15,  278,   17,   12,  326,

       17,   17,   15,   16,   17,   15,   18,   17,   19,   20,
       21,   17,   16,  260,  278,   19,   20,   21,   22,   24,
       17,   12,   61,   27,   21,   22,   24,  325,   28,   61,
       27,  324,  260,   20,   19,   28,   22,   27,   23,   21,
       23,   23,   23,   23,   31,   23,  323,   27,   29,   28,
      318,   31,   65,   23,  317,   29,   37,   31,   31,   65,
       29,   23,   25,   37,   25,   25,   25,   25,  316,   25,
       29,   31,   31,   31,   31,   31,   25,   39,   63,  315,
       29,   65,   38,  308,   39,   63,   25,   25,  307,   38,
       63,   25,   26,   34,   26,   26,   26,   26,   33,   26,

       34,   37,  306,   26,   30,   33,   30,   30,   30,   30,
       30,   30,   32,  305,   26,   40,  296,  295,  293,   32,
       26,   33,   40,   26,   39,   26,   33,   30,   33,   34,
       32,   38,  292,   35,  281,  280,  279,   34,   35,   32,
       35,   35,   35,   35,   34,   35,  263,   34,   36,   41,
      262,   36,   36,   40,  261,   36,   41,   42,   68,   42,
       42,   42,   42,   45,   42,   68,   64,   40,   69,   46,
       45,   55,   66,   64,   70,   69,   46,   71,   44,   66,
       35,   70,   36,   47,   71,   72,   36,   52,   35,   44,
       47,   41,   72,  145,   36,   44,   42,   69,   44,   64,

       44,   45,   44,   42,   43,   66,   43,   43,   43,   43,
       45,   43,   44,   46,   10,    9,   56,  145,   44,   47,
       48,   44,   48,   48,   48,   48,   48,   48,   47,   50,
       49,   56,    3,    0,    0,    0,   50,   49,   47,   51,
       56,   73,   43,   74,    0,    0,   51,    0,   73,    0,
       74,   43,   43,   73,   56,   58,   43,   58,   58,   58,
       58,   58,   75,   76,    0,   77,   48,   49,   49,   75,
       76,   50,   77,    0,    0,    0,    0,    0,    0,   50,
       49,   49,   49,   49,   49,   51,    0,   78,    0,    0,
       51,   75,   51,   59,   78,   59,   59,   59,   59,   59,

        0,    0,   79,   59,   59,   59,   59,   59,   59,   79,
       80,   81,   82,   83,   78,   84,   85,   80,   81,   82,
       83,    0,   84,   85,    0,    0,   86,   59,   59,   59,
       59,   59,   59,   86,   87,   88,    0,    0,   89,   90,
       91,   87,   88,   81,   84,   89,   90,   91,   92,   93,
       94,    0,   96,   95,   97,   92,   93,   94,   87,   96,
       95,   97,   98,   88,   95,   99,  100,  101,    0,   98,
        0,    0,   99,  100,  101,   95,    0,   97,   93,    0,
        0,    0,  102,   97,  102,  102,  102,  102,  102,  102,
      103,  104,  105,   99,  106,  107,    0,  103,  104,  105,

      108,  106,  107,  103,  105,  109,  110,  108,  111,    0,
      112,  114,  109,  110,  113,  111,   99,  112,  114,  115,
      116,  113,  117,    0,  107,  118,  115,  116,  108,  117,
      111,  119,  118,    0,  120,  121,    0,  122,  119,  123,
      112,  120,  121,  113,  122,  124,  123,  125,    0,    0,
      127,  126,  124,  128,  125,  117,  116,  127,  126,  130,
      128,  129,  131,  132,  119,  134,  130,  133,  129,  131,
      132,  121,  134,  135,  133,  137,  136,  118,  138,    0,
      135,  139,  137,  136,  141,  138,  120,  140,  139,  122,
      147,  141,  142,    0,  140,  124,  129,  127,    0,  142,

      154,    0,  125,  126,  128,  147,  129,  154,  149,  152,
      135,  130,  136,  133,  147,  149,  152,    0,  148,  133,
      148,  148,  148,  148,  150,  148,  151,  137,  147,  138,
      152,  150,  140,  154,  150,  156,  149,  141,  155,  157,
      159,  151,  156,    0,  142,  155,  158,  159,  160,  161,
      151,  162,    0,  158,  157,  160,  161,  164,  162,  163,
      158,  165,  156,  157,  151,  169,  163,  155,  165,  163,
      167,  169,  164,    0,  161,  166,  168,  157,  169,  165,
      162,  164,  166,  168,  170,  167,  171,    0,  177,  172,
      168,  170,    0,  171,  167,  164,  172,  173,  174,  166,

      175,    0,  176,  177,  173,  174,    0,  175,  167,  176,
      175,  178,  177,  170,  179,  180,  182,  181,  178,  184,
      183,  179,  180,  182,    0,  178,  177,  183,  179,  185,
      186,  174,  181,  180,  184,  187,  185,  186,  171,  188,
      190,  181,  187,  184,  189,  191,  188,  190,    0,  192,
      196,  194,  191,  193,  183,  181,  192,  184,  194,  189,
      193,  197,  195,  186,  198,  196,  199,  182,  189,  195,
      200,  198,  199,  185,  196,    0,  197,  200,  190,  199,
        0,    0,  189,  201,    0,  197,    0,  187,  196,  188,
      201,  202,    0,  191,    0,  193,  195,  203,  194,  197,

      204,  192,  198,  200,  203,  205,  202,  204,    0,  207,
        0,  208,  205,  209,    0,  202,  207,  201,  208,  212,
      209,  208,    0,  211,  213,  214,  212,  216,    0,  202,
      211,  213,  214,  211,  216,  203,  217,  219,  204,    0,
        0,  218,  209,  217,  219,  213,  212,  205,  218,  221,
      222,  218,  225,  224,  225,  226,  221,  222,  216,  221,
      224,  227,  226,  222,  225,  226,  219,  228,  227,  229,
      225,  232,  231,    0,  228,  233,  229,  234,  232,  231,
      228,  235,  233,  236,  234,  237,  238,    0,  235,    0,
      236,    0,  237,  238,  228,  227,  233,  239,  229,  231,

      240,  242,  241,  243,  239,    0,  245,  240,  242,  241,
      243,  234,  244,  245,  244,  246,    0,  236,  247,  248,
      250,  251,  246,  244,  252,  247,  248,  250,  251,  244,
      238,  252,  253,  235,  240,  237,  241,  254,  242,  253,
      255,  257,    0,  245,  254,  256,  253,  255,  257,  250,
        0,  239,  256,  252,  255,  243,  245,  256,  258,  259,
        0,    0,    0,  248,  264,  258,  259,  246,  247,  249,
      265,  264,    0,  259,  249,  266,  264,  265,  249,  249,
      267,  268,  266,  269,  249,  266,  258,  267,  268,  270,
      269,    0,  271,  249,  267,    0,  270,  272,  249,  271,

        0,  249,  249,  273,  272,  274,  265,  249,  276,  275,
      273,  285,  274,  277,  282,  276,  275,  283,  285,  286,
      277,  282,  287,  288,  283,  290,  286,  289,  291,  287,
      288,  286,  290,  298,  289,  291,    0,    0,    0,  301,
      298,  273,    0,  274,  271,  275,  301,  289,  282,  272,
      288,  277,    0,  287,  297,  283,  299,  300,  302,  276,
      303,  297,  304,  299,  300,  302,    0,  303,    0,  304,
        0,  309,  299,  300,  297,  301,  298,  310,  309,  311,
      312,  313,  314,  319,  310,  320,  311,  312,  313,  314,
      319,  321,  320,  322,  327,    0,  311,    0,  321,    0,

      322,  327,    0,    0,    0,  304,    0,    0,    0,    0,
      303,  309,  302,    0,    0,    0,    0,  310,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  322,  333,    0,  333,  333,  333,
      334,  334,  336,    0,  336,  336,  336,  337,  337,  337,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dspsim.l"
#define INITIAL 0
#line 2 "dspsim.l"
#include "y.tab.h"
#include <stdio.h>	/* perror() */
#include <stdlib.h>	/* strtol(), exit() */
#include <string.h>	/* strcpy() */
#include "dspsim.h"
#include "symtab.h"	
#include "icode.h"	
#include "optab.h"
#include "secinfo.h"

extern char linebuf[MAX_LINEBUF];
extern int lineno;
extern unsigned int curaddr;
extern sICode *curicode;
extern char	condbuf[MAX_CONDBUF];

#line 769 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 20 "dspsim.l"

	/* literal keyword tokens */
	/* AMF, AF, MF */
#line 924 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 333 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1151 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FRND;	
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FSS;	
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FSU;	
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FUS;	
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FUU;	
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FC1;	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FC2;	}
	YY_BREAK
/* COND */
case 8:
YY_RULE_SETUP
#line 57 "dspsim.l"
{	return CIF;	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CEQC;	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CEQ;	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNEC;	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNE;	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CGT;	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 79 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CLE;	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CLT;	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 87 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CGE;	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "dspsim.l"
{		
				yylval.tstr = strdup(yytext);
				return CAVC;	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_AVC;	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CAV;	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_AV;	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CACC;	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_ACC;	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CAC;	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_AC;	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CSVC;	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_SVC;	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 131 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CSV;	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 135 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_SV;	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 139 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CMVC;	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_MVC;	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CMV;	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 151 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_MV;	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 155 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CNOT_CE;	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 159 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return CTRUE;	}
	YY_BREAK
/* PUSH/POP stack */
case 35:
YY_RULE_SETUP
#line 164 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return KPC;	
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 169 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return KLOOP;	
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 174 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return KSTS;	
			}
	YY_BREAK
/* CONJ modifier */
case 38:
YY_RULE_SETUP
#line 180 "dspsim.l"
{	return MCONJ;	}
	YY_BREAK
/* SF */
case 39:
YY_RULE_SETUP
#line 183 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FHI;	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 187 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FLO;	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 191 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return FHIX;	}
	YY_BREAK
/* Registers */
case 42:
YY_RULE_SETUP
#line 196 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return RCNTR;	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 200 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return RCACTL;	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 204 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return RLPSTACK;	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 208 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return RPCSTACK;	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 212 "dspsim.l"
{	return RASTAT;	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 214 "dspsim.l"
{	return RMSTAT;	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 216 "dspsim.l"
{	return RSSTAT;	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 218 "dspsim.l"
{	return RPX;	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 220 "dspsim.l"
{		/* Ix registers */
		yylval.tstr = strdup(yytext);
		return RIX;
	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 225 "dspsim.l"
{		/* Mx registers */
		yylval.tstr = strdup(yytext);
		return RMX;
	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 230 "dspsim.l"
{		/* Lx registers */
		yylval.tstr = strdup(yytext);
		return RLX;
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 235 "dspsim.l"
{		/* Bx registers */
		yylval.tstr = strdup(yytext);
		return RBX;
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 240 "dspsim.l"
{		/* Rx registers */
		yylval.tstr = strdup(yytext);
		return RRX;
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 245 "dspsim.l"
{		/* ACCx registers */
		yylval.tstr = strdup(yytext);
		return RACC;
	}
	YY_BREAK
/* MSTAT Fields: TBD */
case 56:
YY_RULE_SETUP
#line 252 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MSEC_REG;	
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 257 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MSEC_REG;
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 262 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MBIT_REV;	
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 267 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MBIT_REV;	
	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 272 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MAV_LATCH;	
	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 277 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MAV_LATCH;	
	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 282 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MAL_SAT;	
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 287 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MAL_SAT;	
	}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 292 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MM_MODE;	
	}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 297 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MM_MODE;	
	}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 302 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MTIMER;	
	}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 307 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MTIMER;	
	}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 312 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MSEC_DAG;	
	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 317 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MSEC_DAG;	
	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 322 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MM_BIAS;	
	}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 327 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MM_BIAS;	
	}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 332 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return MINT;	
	}
	YY_BREAK
/* other keywords */
case 73:
YY_RULE_SETUP
#line 338 "dspsim.l"
{	
		yylval.tstr = strdup(yytext);
		return KNONE;	
	}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 343 "dspsim.l"
{	return KSEPARATOR;	}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 345 "dspsim.l"
{	return KPM;	}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 347 "dspsim.l"
{	return KDM;	}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 349 "dspsim.l"
{	return KUNTIL;	}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 351 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return KCE;	
			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 356 "dspsim.l"
{	
				yylval.tstr = strdup(yytext);
				return KFOREVER;
			}
	YY_BREAK
/* address operator */
case 80:
YY_RULE_SETUP
#line 362 "dspsim.l"
{	
			yylval.tstr = strdup(yytext);
			return KPOST;	
		}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 367 "dspsim.l"
{	
			yylval.tstr = strdup(yytext);
			return KPRE;	
		}
	YY_BREAK
/* numbers */
case 82:
YY_RULE_SETUP
#line 373 "dspsim.l"
{
		yylval.ival = (int)strtol(yytext, NULL, 10);
		return DEC_NUMBER;
	}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 378 "dspsim.l"
{
		yylval.ival = (int)strtol(&yytext[2], NULL, 16);
		return HEX_NUMBER;
	}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 383 "dspsim.l"
{
		yylval.ival = (int)strtol(&yytext[2], NULL, 2);
		return BIN_NUMBER;
	}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 388 "dspsim.l"
;	/* ignore whitespace */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 390 "dspsim.l"
{	/* return symbol pointer */
		yytext[yyleng-1] = '\0';	/* remove trailing colon */

		sTab *sp = symlook(yytext, curaddr);
		yylval.symp = sp;
		if(VerboseMode) printf("> LABEL0: %p\n", sp);
		return LABEL;
	}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 399 "dspsim.l"
{	/* should return opcode */
		unsigned int code = isOpcode(yytext);
		if(VerboseMode) printf("yytext:\t%s\n", yytext);
		if(VerboseMode) printf("code:\t%d\n", code);
		if(code != FALSE){		/* opcode */
			yylval.op = code;
			if(!curicode){ 
				if(isParsingMultiFunc){
					isParsingMultiFunc = FALSE;
					curaddr++;
				}

				/* if .CODE, reset curaddr */
				if(code == i_CODE) curaddr = 0;

				curicode = sICodeListAdd(&iCode, code, curaddr, lineno);
				if(VerboseMode) printf("curaddr = %X\n", curaddr);

				if(!isPseudoInst(code) || code == i_VAR)
					curaddr++;	/**< increment Address Counter */

				curicode->Line = strdup(linebuf);
				if(VerboseMode) printf("> LINE1:\t%s\n", linebuf);
			}else{
				isParsingMultiFunc = TRUE;

				sICode *oldicode = curicode;	/* save pointer to first 
													instruction of multifunction */
				curaddr = oldicode->PMA;
				curicode = sICodeListMultiAdd(&iCode, code, curaddr, lineno);
				if(VerboseMode) printf("NOTE: curicode not NULL at addr %X, line %d\n", curaddr, lineno);
			}
			if(condbuf[0] != '\0') {
				curicode->Cond = strdup(condbuf);
				if(VerboseMode) printf("COND:\t%s\n", condbuf);
			}
			return OPCODE;
		} else {
			sTab *sp = sTabHashSearch(symTable, yytext);
			if(sp){	/* it's already in symbol table */
				yylval.symp = sp;
				if(VerboseMode) printf("> LABEL2: %p\n", sp);
			}else{	/* make new one */
				sp = symlook(yytext, UNDEFINED);	/* symbol offset (should be symTable) */
				yylval.symp = sp;
				if(VerboseMode) printf("> LABEL1: %p\n", sp);
			}
			return OFFSET;
		}
	}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 450 "dspsim.l"
{	/* return comment */
		yylval.tstr = strdup(yytext);
		return COMMENT;
	}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 455 "dspsim.l"
{ return 0; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 457 "dspsim.l"
{	
			int c = yytext[0];
			strcpy(linebuf, yytext+1);
			yyless(1);

			if(VerboseMode) printf("> %s\n", linebuf);
			return c;
	}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 466 "dspsim.l"
{ return yytext[0]; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 467 "dspsim.l"
ECHO;
	YY_BREAK
#line 1729 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 333 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 333 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 332);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 467 "dspsim.l"


void yyerror(char *s)
{
	fprintf(stderr, "%d: %s at \"%s\"\n", lineno, s, yytext);
}

/* look up a symbol table entry, add if not present */
struct sTab* symlook(char *s, unsigned int n)
{
    struct sTab *sp;

	return sTabHashAdd(symTable, s, n);
} /* symlook */

void addlabel(char *name, unsigned int address)
{
	struct sTab	*sp = symlook(name, address);
}

void yyerror2(char *s)
{
	fprintf(stderr,"%d: %s\n",lineno, s);
}

unsigned int isOpcode(char *s)
{
	oTab* p;
	p = oTabHashSearch(opTable, s);
	if(p == NULL) return FALSE;
	else 
		return p->Index;
}
